#Properties
app.version=3.5
argLine=-javaagent\:/Users/brobert/.m2/repository/org/jacoco/org.jacoco.agent/0.8.13/org.jacoco.agent-0.8.13-runtime.jar\=destfile\=/Users/brobert/Documents/code/lawless-legends/Platform/Apple/tools/jace/target/jacoco.exec,excludes\=jace/assembly/AcmeCrossAssembler.class
build.timestamp=2026-08-31
javafx.version=22.0.2
lwjgl.natives=natives-macos-arm64
lwjgl.version=3.3.3
mainClass=jace.LawlessLegends
maven.build.timestamp.format=yyyy-MM-dd
netbeans.hint.license=apache20
project.build.sourceEncoding=UTF-8
