#!/usr/bin/env bash

cd /Users/mhaye/plat/tools/ProRWTS && make && \
cd /Users/mhaye/plat/tools/PLASMA/src && make vm && \
cd /Users/mhaye/plat/tools/PackPartitions && rm -f dist/PackPartitions.jar && ant jar
